# Note: Name of file should match name of robot in URDF

# Robot Execution Speed
main_velocity_scaling_factor: 0.7 # moving between cartesian paths
approach_velocity_scaling_factor: 0.2
lift_velocity_scaling_factor: 0.1
retreat_velocity_scaling_factor: 0.6
calibration_velocity_scaling_factor: 0.5  #0.1

# Sleep timers
wait_before_grasp: 0.1
wait_after_grasp: 1.0

# Poses
start_pose: home
right_arm_dropoff_pose: home
left_arm_dropoff_pose: left_goal_bin_pose_DISABLED

# Cartesian path config
jump_threshold: 4

# Safety
collision_wall_safety_margin: 0.01 # 0.02

# Semantics
dual_arm: false
right_hand_name: gripper
left_hand_name: gripper_DISABLED
right_arm_name: arm
right_arm_only_name: arm
left_arm_name: manipulator_DISABLED
both_arms_name: manipulator_DISABLED

# Topics
joint_state_topic: /joint_states

# Test data
test:
  test_joint_limit_joint: 1  # starts at 0, negative number means test all
  test_double: 0.05 # for anything
  # During development it is nice to have ability to tweak a value
  test_pose: [0.0, 0.0, -0.2, 0, 0, 0] # x,y,z,r,p,y
  
# Tactile Sensor Data
sheer_force_threshold: 6
touch_teleop_max_translation_step: 0.005

# Insertion
insertion_duration: 15 # sec
insertion_distance: 0.1 # meters
insertion_steps_per_meter: 1000 # discretization
insertion_touch_translation_step: 0.01

# Insertion haulting
sheer_force_rejection_max: 10

# Insertion Demo Timing
insertion_updown_pause: 1 #sec
insertion_alter_pause: 1 #sec

# Torque insertion capability
insertion_torque_max: 50 # cap all torque readings at this amount, absolute
insertion_torque_min: 20 # ignore torque readings below this amount, absolute
insertion_attempt_radius: 0.0000001 
insertion_attempt_distance: 0.0001 
insertion_attempt_distance_scale: 10000 # unused
insertion_torque_scale: -0.00075 # scale the torque of value (min, max) to an output rotation amount

# Insertion spiral
insertion_spiral_distance: 0.005

# Automated Insertion test
automated_insertion_distance: 0.08 # meters
automated_retract_distance: 0.18 # meters
automated_insertion_theta: 0.78539816339 # degrees

# Teleoperation
#teleoperation_offset: [0.0, 0.0, -0.25, 0, 0, 0] # x,y,z,r,p,y  - tip of finger
teleoperation_offset: [0.0, 0.0, -0.36, 0, 0, 0] # x,y,z,r,p,y  - tip of knife

behavior:
  end_effector_enabled: true
  super_auto: true
  dropping_bounding_box: true
  use_camera_hack_offset: false
  use_computer_vision_shelf: false